<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="test" nsURI="ecore://test.ecore-gen.html.nasdanika.org" nsPrefix="ecore-gen-test">
  <eClassifiers xsi:type="ecore:EEnum" name="Color">
    <eLiterals name="White"/>
    <eLiterals name="Brown" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LivingBeing">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="#//Color"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Food" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Animal" eSuperTypes="#//LivingBeing">
    <eTypeParameters name="F">
      <eBounds eClassifier="#//Food"/>
    </eTypeParameters>
    <eOperations name="eats">
      <eParameters name="food">
        <eGenericType eTypeParameter="#//Animal/F"/>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="genericAttribute">
      <eGenericType eTypeParameter="#//Animal/F"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plant" eSuperTypes="#//LivingBeing"/>
  <eClassifiers xsi:type="ecore:EClass" name="Grass" eSuperTypes="#//Plant #//Food"/>
  <eClassifiers xsi:type="ecore:EClass" name="Hare">
    <eGenericSuperTypes eClassifier="#//Animal">
      <eTypeArguments eClassifier="#//Grass"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//Food"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fox">
    <eGenericSuperTypes eClassifier="#//Animal">
      <eTypeArguments eClassifier="#//Hare"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
